[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "colss"
version = "0.1.0"
description = "C++ accelerated CSV engine"
authors = [{name = "Siva"}]
requires-python = ">=3.8"
